### ISSUE TITLE
Open Google Chrome profile request

### ISSUE THREAD

**Issue by ccarpiog** [Wit4r7/AlfredAutomations#1]
Would it be possible to modify the workflow so that if a profile has an already created window then the workflow switched to that window instead of creating another one?

**Comment by Wit4r7** [comment]
Hi, 

I think that should be possible with using a little bit of Apple Script. Currently, I'm using zsh to open a new window. It would require to add a step in-between and check with AS if a Chrome window is open, if yes switch to that otherwise create a new one. 

Unfortunately, I'm busy the next 2–3 weeks and have no time to implement this. If you can wait, I will have a look at it, otherwise please don't hesitate to try it by yourself.

**Comment by ccarpiog** [comment]
Thanks a lot for your answer. Unfortunately I don't know the first thing about Apple Script, so I'll have to wait.

In any case, awesome Workflow, I like it very much. Thanks for creating it!

**Comment by Wit4r7** [comment]
@ccarpiog 

Please excuse my very late reply. I was busy over the past. 

Unfortunately, I was unable to find a way to activate an existing window. I tried different ways, including Apple Script, ZSH and Bash. 

It is not the same, but maybe take a look at AltTab. This is a tool with enables to tab easily between the open windows in MacOS. This was I use and it helps a lot. 
https://alt-tab-macos.netlify.app/

best regards.

**Comment by ccarpiog** [comment]
@Wit4r7 Thanks a lot for your answer.

Finally I settled for a basic workflow that consists in a List Filter that accepts whe keywords I choose and outputs the name of the profile as shown on the Chrome "Profiles" menu item.

That output is the input for this Apple Script:

```
activate application "Google Chrome"
tell application "System Events" to tell process "Google Chrome"
    click menu item "{query}" of menu 1 of menu bar item "Profiles" of menu bar 1
end tell
```

It's not pretty, but it works. :)

I'd much prefer if the workflow could populate the list filter by reading the list of profiles because my profiles have different names in different computers, but I'm not complaining.

**Comment by Wit4r7** [comment]
Ah cool. Nice solution!
