### ISSUE TITLE
Followup on Gallery submission

### ISSUE THREAD

**Issue by vitorgalvao** [Wit4r7/AlfredAutomations#2]
Hello @Wit4r7,

Seems you might’ve missed the [request for changes](https://www.alfredforum.com/topic/19374-open-chrome-profiles/#comment-103483) necessary for inclusion in the Gallery, so commenting here as an alternative channel.

Have a nice weekend.

**Comment by Wit4r7** [comment]
Thanks for the reminder. I updated the workflow.
